#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_COMMAND_LENGTH 512

/*
 * THIS CODE WAS GENERATED BY GEMINI
 * This is the first version of the C backup engine.
 * It is a simple program that orchestrates a remote differential backup
 * using rsync over SSH.
 *
 * It constructs a shell command and uses the system() function to execute it.
 * In this initial version, all configurations are hardcoded.
 */
int main() {
    // --- Configuration Variables (Hardcoded for now) ---
    const char *userB = "gustavo";
    const char *hostB = "192.168.0.1";
    const char *sourcePath = "/home/gustavo/Documents/";

    const char *userC = "root";
    const char *hostC = "192.168.0.1";
    const char *destinationPath = "/home/ubuntu/backups/";

    char command[MAX_COMMAND_LENGTH];
    int result;

    printf("Iniciando o processo de backup diferencial...\n");
    printf("-------------------------------------------\n");

    // --- Construct the full shell command string ---
    // The command is built using sprintf, which formats and stores
    // the string in the 'command' buffer.
    // The structure is: ssh <user>@<host> "rsync <flags> <source> <user>@<destination>"
    snprintf(command, MAX_COMMAND_LENGTH,
             "ssh %s@%s \"rsync -avz %s %s@%s:%s\"",
             userB, hostB, sourcePath, userC, hostC, destinationPath);

    printf("Comando a ser executado:\n%s\n", command);
    printf("-------------------------------------------\n");

    // --- Execute the command using the system() function ---
    // The system() function passes the string to the shell for execution.
    // It returns the exit code of the command.
    result = system(command);

    // --- Check the result of the command execution ---
    if (result == 0) {
        printf("Backup concluído com sucesso!\n");
    } else {
        // The system() call can return a non-zero value for various reasons.
        // For our purpose, any non-zero value indicates an error.
        printf("Erro no backup. Código de retorno: %d\n", result);
        fprintf(stderr, "Falha ao executar o comando. Por favor, verifique a ligação SSH, permissões, e os caminhos de origem/destino.\n");
        return 1; // Return with an error code
    }

    return 0; // Return with success code
}
